// <auto-generated />
namespace Topicos3Parcial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class inicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inicial));
        
        string IMigrationMetadata.Id
        {
            get { return "202411031651017_inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
